# This is a basic workflow to help you get started with Actions

name: Bun build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Archlinux
        run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
        
      - name: Install Deps
        run: |
          pacman -Syu --noconfirm --needed
          pacman -S --noconfirm --needed llvm clang lld
          pacman -S --noconfirm --needed base-devel ccache cmake esbuild git go libiconv libtool make ninja pkg-config python rust sed unzip
          pacman -S --noconfirm --needed zig
          pacman -S --noconfirm --needed nodejs npm

      - name: Clone repo
        run: |
          git clone https://github.com/oven-sh/bun.git
          cd ./bun/

      - name: make setup
        run: make setup

      - name: make release-bindings -j12
        run: make release-bindings -j12

      - name: make release
        run: make release
