# This is a basic workflow to help you get started with Actions

name: Bun build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
  
env:
  JSC_BASE_DIR: bun-webkit

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:  ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
#      - name: Install Archlinux
#        run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
#        
#      - name: Install Deps
#        run: |
#          sudo pacman -Syu --noconfirm --needed
#          sudo pacman -S --noconfirm --needed llvm clang lld
#          sudo pacman -S --noconfirm --needed base-devel ccache cmake esbuild git go libiconv libtool make ninja pkg-config python rust sed unzip
#          sudo pacman -S --noconfirm --needed zig
#          sudo pacman -S --noconfirm --needed nodejs npm

      - name: Install Ubuntu Deps
        run: |
          sudo apt install llvm-15 lld-15 clang-15
          sudo apt install cargo ccache cmake esbuild git golang libtool ninja-build pkg-config rustc
          sudo apt install nodejs npm
          npm install -g @oven/zig
          
      - name: Test Vars
        run: |
          zig version
          which clang-15
          echo $JSC_BASE_DIR

      - name: Clone repo
        run: |
          git clone https://github.com/noeljacob/bun
          cd bun
          git checkout pnpx-patch
    
      - name: make setup
        run: |
          cd bun
          make setup
          
      - name: make headers
        run: |
          cd bun
          make headers
          
      - name: make codegen
        run: |
          cd bun
          make codegen
          
      - name: make generate-sink
        run: |
          cd bun
          make generate-sink

      - name: make release-bindings -j12
        run: |
          cd bun 
          make release-bindings -j12

      - name: make release
        run: |
          cd bun
          make release
